db:
  type: postgres
  host: "{{ env_var('DB_HOST') }}"
  user: "{{ env_var('DB_USER') }}"
  password: "{{ env_var('DB_PASSWORD') }}"
  port: "{{ env_var('DB_PORT') | int }}"
  dbname: "{{ env_var('DB_NAME') }}"
